# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: blocksettings																							#Pflichtfeld
version: '1.0'																									#Pflichtfeld
author: © Falko Müller
supportpage: https://github.com/iceman-fx/blocksettings

page:
    title: 'translate:a1604_title'
    perm: blocksettings[]
    icon: rex-icon fa-database
    subpages:
        default: { title: 'translate:a1604_default' }
        config: { title: 'translate:a1604_config', icon: rex-icon fa-wrench }	#config-Seite mit separaten Rechten
        help: { title: 'translate:a1604_help', icon: rex-icon fa-question-circle, itemclass: pull-right }

requires:
    redaxo: '^5.10.0' 																						#benötigt mindestens REDAXO 5.3