# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: blocksettings																							#Pflichtfeld
version: '1.0 beta'																									#Pflichtfeld
author: © Falko Müller
supportpage: https://github.com/iceman-fx/blocksettings

page:
    title: 'Block-Einstellungen'
    perm: blocksettings[]
    icon: rex-icon fa-database
    subpages:
        default: { title: 'translate:a1604_default' }
        help: { title: 'translate:a1604_help', icon: rex-icon fa-question-circle, itemclass: pull-right }

requires:
    redaxo: '^5.3.0' 																						#benötigt mindestens REDAXO 5.3